
export const currencySymbols: Record<string, string> = {
  USD: "US Dollar",
  EUR: "Euro",
  GBP: "British Pound",
  JPY: "Japanese Yen",
  AUD: "Australian Dollar",
  CAD: "Canadian Dollar",
  CHF: "Swiss Franc",
  CNY: "Chinese Yuan",
  INR: "Indian Rupee",
  MAD: "Moroccan Dirham",
  AED: "UAE Dirham",
  SAR: "Saudi Riyal",
  EGP: "Egyptian Pound",
  TRY: "Turkish Lira",
  RUB: "Russian Ruble",
  BRL: "Brazilian Real",
  MXN: "Mexican Peso",
  ZAR: "South African Rand",
  SGD: "Singapore Dollar",
  HKD: "Hong Kong Dollar",
  BTC: "Bitcoin",
  ETH: "Ethereum"
};

export const goldUnits = [
  { value: "gram", label: "Gram" },
  { value: "ounce", label: "Troy Ounce" },
  { value: "kilo", label: "Kilogram" }
];

export const timeframes = [
  { value: "1d", label: "1 Day" },
  { value: "1w", label: "1 Week" },
  { value: "1m", label: "1 Month" },
  { value: "6m", label: "6 Months" },
  { value: "1y", label: "1 Year" }
];

export const conversionFactors = {
  gram: 1,
  ounce: 31.1035,
  kilo: 1000
};

export const countries = [
  { code: "US", name: "United States", currency: "USD", flag: "🇺🇸" },
  { code: "EU", name: "European Union", currency: "EUR", flag: "🇪🇺" },
  { code: "GB", name: "United Kingdom", currency: "GBP", flag: "🇬🇧" },
  { code: "JP", name: "Japan", currency: "JPY", flag: "🇯🇵" },
  { code: "IN", name: "India", currency: "INR", flag: "🇮🇳" },
  { code: "AU", name: "Australia", currency: "AUD", flag: "🇦🇺" },
  { code: "CA", name: "Canada", currency: "CAD", flag: "🇨🇦" },
  { code: "CH", name: "Switzerland", currency: "CHF", flag: "🇨🇭" },
  { code: "CN", name: "China", currency: "CNY", flag: "🇨🇳" },
  { code: "MA", name: "Morocco", currency: "MAD", flag: "🇲🇦" },
  { code: "AE", name: "United Arab Emirates", currency: "AED", flag: "🇦🇪" },
  { code: "SA", name: "Saudi Arabia", currency: "SAR", flag: "🇸🇦" },
  { code: "EG", name: "Egypt", currency: "EGP", flag: "🇪🇬" },
  { code: "TR", name: "Turkey", currency: "TRY", flag: "🇹🇷" },
  { code: "RU", name: "Russia", currency: "RUB", flag: "🇷🇺" },
  { code: "BR", name: "Brazil", currency: "BRL", flag: "🇧🇷" },
  { code: "MX", name: "Mexico", currency: "MXN", flag: "🇲🇽" },
  { code: "ZA", name: "South Africa", currency: "ZAR", flag: "🇿🇦" },
  { code: "SG", name: "Singapore", currency: "SGD", flag: "🇸🇬" },
  { code: "HK", name: "Hong Kong", currency: "HKD", flag: "🇭🇰" }
];

export const languages = [
  { code: "en", name: "English", flag: "🇺🇸" },
  { code: "fr", name: "Français", flag: "🇫🇷" },
  { code: "es", name: "Español", flag: "🇪🇸" },
  { code: "ar", name: "العربية", flag: "🇸🇦" },
  { code: "zh", name: "中文", flag: "🇨🇳" }
];

export const goldImages = [
  { id: "gold-bars", src: "https://images.unsplash.com/photo-1610375461246-83df859d849d", alt: "Gold Bars" },
  { id: "gold-coins", src: "https://images.unsplash.com/photo-1612696874005-d659af6d2f7c", alt: "Gold Coins" },
  { id: "gold-jewelry", src: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f", alt: "Gold Jewelry" },
  { id: "gold-ingot", src: "https://images.unsplash.com/photo-1574362848149-11496d93a7c7", alt: "Gold Ingot" }
];

export const translations = {
  en: {
    goldPriceTracker: "Gold Price Tracker",
    trackRealTime: "Track real-time gold prices across different countries and units",
    currentGoldPrice: "Current Gold Price",
    country: "Country",
    unit: "Unit",
    priceTrend: "Price Trend",
    historicalGoldPrice: "Historical gold price",
    goldPriceByUnit: "Gold Price by Unit",
    compareGoldPrices: "Compare gold prices in different measurement units",
    priceStatistics: "Price Statistics",
    keyMetrics: "Key metrics for gold price in",
    average: "Average",
    minimum: "Minimum",
    maximum: "Maximum",
    change: "Change",
    search: "Search",
    language: "Language",
    selectCountry: "Select country",
    selectUnit: "Select unit",
    selectLanguage: "Select language",
    lastUpdated: "Last updated",
    gram: "Gram",
    ounce: "Troy Ounce",
    kilogram: "Kilogram",
    days: "Days",
    priceOf: "Price of"
  },
  fr: {
    goldPriceTracker: "Suivi du Prix de l'Or",
    trackRealTime: "Suivez les prix de l'or en temps réel dans différents pays et unités",
    currentGoldPrice: "Prix Actuel de l'Or",
    country: "Pays",
    unit: "Unité",
    priceTrend: "Tendance des Prix",
    historicalGoldPrice: "Prix historique de l'or",
    goldPriceByUnit: "Prix de l'Or par Unité",
    compareGoldPrices: "Comparez les prix de l'or dans différentes unités de mesure",
    priceStatistics: "Statistiques des Prix",
    keyMetrics: "Indicateurs clés pour le prix de l'or en",
    average: "Moyenne",
    minimum: "Minimum",
    maximum: "Maximum",
    change: "Variation",
    search: "Rechercher",
    language: "Langue",
    selectCountry: "Sélectionner un pays",
    selectUnit: "Sélectionner une unité",
    selectLanguage: "Sélectionner une langue",
    lastUpdated: "Dernière mise à jour",
    gram: "Gramme",
    ounce: "Once Troy",
    kilogram: "Kilogramme",
    days: "Jours",
    priceOf: "Prix de"
  },
  es: {
    goldPriceTracker: "Seguimiento del Precio del Oro",
    trackRealTime: "Sigue los precios del oro en tiempo real en diferentes países y unidades",
    currentGoldPrice: "Precio Actual del Oro",
    country: "País",
    unit: "Unidad",
    priceTrend: "Tendencia de Precios",
    historicalGoldPrice: "Precio histórico del oro",
    goldPriceByUnit: "Precio del Oro por Unidad",
    compareGoldPrices: "Compara los precios del oro en diferentes unidades de medida",
    priceStatistics: "Estadísticas de Precios",
    keyMetrics: "Métricas clave para el precio del oro en",
    average: "Promedio",
    minimum: "Mínimo",
    maximum: "Máximo",
    change: "Cambio",
    search: "Buscar",
    language: "Idioma",
    selectCountry: "Seleccionar país",
    selectUnit: "Seleccionar unidad",
    selectLanguage: "Seleccionar idioma",
    lastUpdated: "Última actualización",
    gram: "Gramo",
    ounce: "Onza Troy",
    kilogram: "Kilogramo",
    days: "Días",
    priceOf: "Precio de"
  },
  ar: {
    goldPriceTracker: "متتبع أسعار الذهب",
    trackRealTime: "تتبع أسعار الذهب في الوقت الحقيقي عبر مختلف البلدان والوحدات",
    currentGoldPrice: "سعر الذهب الحالي",
    country: "البلد",
    unit: "وحدة",
    priceTrend: "اتجاه السعر",
    historicalGoldPrice: "سعر الذهب التاريخي",
    goldPriceByUnit: "سعر الذهب حسب الوحدة",
    compareGoldPrices: "قارن أسعار الذهب بوحدات قياس مختلفة",
    priceStatistics: "إحصائيات الأسعار",
    keyMetrics: "المقاييس الرئيسية لسعر الذهب في",
    average: "المتوسط",
    minimum: "الحد الأدنى",
    maximum: "الحد الأقصى",
    change: "التغيير",
    search: "بحث",
    language: "اللغة",
    selectCountry: "اختر البلد",
    selectUnit: "اختر الوحدة",
    selectLanguage: "اختر اللغة",
    lastUpdated: "آخر تحديث",
    gram: "جرام",
    ounce: "أونصة تروي",
    kilogram: "كيلوجرام",
    days: "أيام",
    priceOf: "سعر"
  },
  zh: {
    goldPriceTracker: "黄金价格追踪器",
    trackRealTime: "追踪不同国家和单位的实时黄金价格",
    currentGoldPrice: "当前黄金价格",
    country: "国家",
    unit: "单位",
    priceTrend: "价格趋势",
    historicalGoldPrice: "历史黄金价格",
    goldPriceByUnit: "按单位计算的黄金价格",
    compareGoldPrices: "比较不同计量单位的黄金价格",
    priceStatistics: "价格统计",
    keyMetrics: "黄金价格的关键指标，以",
    average: "平均值",
    minimum: "最低",
    maximum: "最高",
    change: "变化",
    search: "搜索",
    language: "语言",
    selectCountry: "选择国家",
    selectUnit: "选择单位",
    selectLanguage: "选择语言",
    lastUpdated: "最后更新",
    gram: "克",
    ounce: "金衡盎司",
    kilogram: "千克",
    days: "天",
    priceOf: "价格"
  }
};
