
// Updated currency and country data with accurate information
// Countries are sorted by region for better organization

export const currencySymbols: { [key: string]: string } = {
  USD: "US Dollar",
  EUR: "Euro",
  GBP: "British Pound",
  JPY: "Japanese Yen",
  AUD: "Australian Dollar",
  CAD: "Canadian Dollar",
  CHF: "Swiss Franc",
  CNY: "Chinese Yuan",
  MAD: "Moroccan Dirham",
  AED: "UAE Dirham",
  SAR: "Saudi Riyal",
  EGP: "Egyptian Pound",
  TRY: "Turkish Lira",
  DZD: "Algerian Dinar",
  TND: "Tunisian Dinar",
  QAR: "Qatari Riyal",
  KWD: "Kuwaiti Dinar",
  OMR: "Omani Rial",
  BHD: "Bahraini Dinar",
  JOD: "Jordanian Dinar",
  LBP: "Lebanese Pound",
  IQD: "Iraqi Dinar",
  LYD: "Libyan Dinar",
  INR: "Indian Rupee",
  RUB: "Russian Ruble",
  BRL: "Brazilian Real",
  MXN: "Mexican Peso",
  ZAR: "South African Rand",
  SGD: "Singapore Dollar",
  HKD: "Hong Kong Dollar",
  KRW: "South Korean Won",
  IDR: "Indonesian Rupiah",
  MYR: "Malaysian Ringgit",
  THB: "Thai Baht",
  PHP: "Philippine Peso",
  VND: "Vietnamese Dong",
  NGN: "Nigerian Naira",
  BTC: "Bitcoin",
  ETH: "Ethereum"
};

// Updated countries list with flags
export const countries = [
  // Middle East and North Africa
  { code: "MA", name: "Morocco", currency: "MAD", flag: "🇲🇦" },
  { code: "EG", name: "Egypt", currency: "EGP", flag: "🇪🇬" },
  { code: "SA", name: "Saudi Arabia", currency: "SAR", flag: "🇸🇦" },
  { code: "AE", name: "United Arab Emirates", currency: "AED", flag: "🇦🇪" },
  { code: "QA", name: "Qatar", currency: "QAR", flag: "🇶🇦" },
  { code: "KW", name: "Kuwait", currency: "KWD", flag: "🇰🇼" },
  { code: "BH", name: "Bahrain", currency: "BHD", flag: "🇧🇭" },
  { code: "OM", name: "Oman", currency: "OMR", flag: "🇴🇲" },
  { code: "DZ", name: "Algeria", currency: "DZD", flag: "🇩🇿" },
  { code: "TN", name: "Tunisia", currency: "TND", flag: "🇹🇳" },
  { code: "JO", name: "Jordan", currency: "JOD", flag: "🇯🇴" },
  { code: "LB", name: "Lebanon", currency: "LBP", flag: "🇱🇧" },
  { code: "IQ", name: "Iraq", currency: "IQD", flag: "🇮🇶" },
  { code: "LY", name: "Libya", currency: "LYD", flag: "🇱🇾" },
  
  // Europe
  { code: "EU", name: "European Union", currency: "EUR", flag: "🇪🇺" },
  { code: "GB", name: "United Kingdom", currency: "GBP", flag: "🇬🇧" },
  { code: "CH", name: "Switzerland", currency: "CHF", flag: "🇨🇭" },
  { code: "TR", name: "Turkey", currency: "TRY", flag: "🇹🇷" },
  { code: "RU", name: "Russia", currency: "RUB", flag: "🇷🇺" },
  
  // Americas
  { code: "US", name: "United States", currency: "USD", flag: "🇺🇸" },
  { code: "CA", name: "Canada", currency: "CAD", flag: "🇨🇦" },
  { code: "BR", name: "Brazil", currency: "BRL", flag: "🇧🇷" },
  { code: "MX", name: "Mexico", currency: "MXN", flag: "🇲🇽" },
  
  // Asia Pacific
  { code: "JP", name: "Japan", currency: "JPY", flag: "🇯🇵" },
  { code: "CN", name: "China", currency: "CNY", flag: "🇨🇳" },
  { code: "IN", name: "India", currency: "INR", flag: "🇮🇳" },
  { code: "AU", name: "Australia", currency: "AUD", flag: "🇦🇺" },
  { code: "SG", name: "Singapore", currency: "SGD", flag: "🇸🇬" },
  { code: "HK", name: "Hong Kong", currency: "HKD", flag: "🇭🇰" },
  { code: "KR", name: "South Korea", currency: "KRW", flag: "🇰🇷" },
  { code: "ID", name: "Indonesia", currency: "IDR", flag: "🇮🇩" },
  { code: "MY", name: "Malaysia", currency: "MYR", flag: "🇲🇾" },
  { code: "TH", name: "Thailand", currency: "THB", flag: "🇹🇭" },
  { code: "PH", name: "Philippines", currency: "PHP", flag: "🇵🇭" },
  { code: "VN", name: "Vietnam", currency: "VND", flag: "🇻🇳" },
  
  // Africa
  { code: "ZA", name: "South Africa", currency: "ZAR", flag: "🇿🇦" },
  { code: "NG", name: "Nigeria", currency: "NGN", flag: "🇳🇬" },
  
  // Crypto
  { code: "BTC", name: "Bitcoin", currency: "BTC", flag: "₿" },
  { code: "ETH", name: "Ethereum", currency: "ETH", flag: "Ξ" }
];

// Gold units with display options
export const goldUnits = [
  { value: "gram", label: "Gram" },
  { value: "ounce", label: "Troy Ounce" },
  { value: "kilo", label: "Kilogram" }
];

// Common conversions
export const commonConversions = [
  { from: "USD", to: "EUR" },
  { from: "EUR", to: "USD" },
  { from: "GBP", to: "EUR" },
  { from: "USD", to: "JPY" },
  { from: "EUR", to: "GBP" }
];

// Updated conversion factors for gold weights
export const conversionFactors = {
  gram: 1,
  ounce: 31.1035, // Troy ounce
  kilo: 1000,
};

// Adding missing exports that are referenced in other files

// Language support
export const languages = [
  { code: "en", name: "English", flag: "🇬🇧" },
  { code: "ar", name: "العربية", flag: "🇸🇦" },
  { code: "fr", name: "Français", flag: "🇫🇷" },
  { code: "es", name: "Español", flag: "🇪🇸" },
  { code: "zh", name: "中文", flag: "🇨🇳" }
];

// Translations
export const translations = {
  en: {
    goldPrice: "Gold Price",
    currentPrice: "Current Price",
    change: "Change",
    changePercent: "Change %",
    buy: "Buy",
    sell: "Sell",
    currency: "Currency",
    weight: "Weight",
    purity: "Purity",
    calculate: "Calculate",
    result: "Result",
    from: "From",
    to: "To",
    amount: "Amount",
    convert: "Convert",
    popular: "Popular",
    favorites: "Favorites",
    addToFavorites: "Add to Favorites",
    removeFromFavorites: "Remove from Favorites",
    goldCalculator: "Gold Calculator",
    currencyConverter: "Currency Converter",
    charts: "Charts",
    timeframe: "Timeframe",
    day: "1 Day",
    week: "1 Week",
    month: "1 Month",
    sixMonths: "6 Months",
    year: "1 Year",
    language: "Language",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    system: "System",
    highPrice: "High",
    lowPrice: "Low",
    avgPrice: "Average",
    home: "Home",
    settings: "Settings",
    languageChanged: "Language changed to",
    goldPricePerGram: "Gold Price per Gram"
  },
  ar: {
    goldPrice: "سعر الذهب",
    currentPrice: "السعر الحالي",
    change: "التغير",
    changePercent: "نسبة التغير",
    buy: "شراء",
    sell: "بيع",
    currency: "العملة",
    weight: "الوزن",
    purity: "النقاء",
    calculate: "حساب",
    result: "النتيجة",
    from: "من",
    to: "إلى",
    amount: "المبلغ",
    convert: "تحويل",
    popular: "شائع",
    favorites: "المفضلة",
    addToFavorites: "إضافة إلى المفضلة",
    removeFromFavorites: "إزالة من المفضلة",
    goldCalculator: "حاسبة الذهب",
    currencyConverter: "محول العملات",
    charts: "الرسوم البيانية",
    timeframe: "الفترة الزمنية",
    day: "يوم",
    week: "أسبوع",
    month: "شهر",
    sixMonths: "6 أشهر",
    year: "سنة",
    language: "اللغة",
    theme: "المظهر",
    light: "فاتح",
    dark: "داكن",
    system: "النظام",
    highPrice: "أعلى سعر",
    lowPrice: "أدنى سعر",
    avgPrice: "متوسط السعر",
    home: "الرئيسية",
    settings: "الإعدادات",
    languageChanged: "تم تغيير اللغة إلى",
    goldPricePerGram: "سعر الذهب للجرام"
  },
  fr: {
    goldPrice: "Prix de l'Or",
    currentPrice: "Prix Actuel",
    change: "Variation",
    changePercent: "Variation %",
    buy: "Acheter",
    sell: "Vendre",
    currency: "Devise",
    weight: "Poids",
    purity: "Pureté",
    calculate: "Calculer",
    result: "Résultat",
    from: "De",
    to: "À",
    amount: "Montant",
    convert: "Convertir",
    popular: "Populaire",
    favorites: "Favoris",
    addToFavorites: "Ajouter aux favoris",
    removeFromFavorites: "Retirer des favoris",
    goldCalculator: "Calculatrice d'Or",
    currencyConverter: "Convertisseur de devises",
    charts: "Graphiques",
    timeframe: "Période",
    day: "1 Jour",
    week: "1 Semaine",
    month: "1 Mois",
    sixMonths: "6 Mois",
    year: "1 An",
    language: "Langue",
    theme: "Thème",
    light: "Clair",
    dark: "Sombre",
    system: "Système",
    highPrice: "Haut",
    lowPrice: "Bas",
    avgPrice: "Moyenne",
    home: "Accueil",
    settings: "Paramètres",
    languageChanged: "Langue changée en",
    goldPricePerGram: "Prix de l'or par gramme"
  },
  es: {
    goldPrice: "Precio del Oro",
    currentPrice: "Precio Actual",
    change: "Cambio",
    changePercent: "Cambio %",
    buy: "Comprar",
    sell: "Vender",
    currency: "Moneda",
    weight: "Peso",
    purity: "Pureza",
    calculate: "Calcular",
    result: "Resultado",
    from: "De",
    to: "A",
    amount: "Cantidad",
    convert: "Convertir",
    popular: "Popular",
    favorites: "Favoritos",
    addToFavorites: "Añadir a favoritos",
    removeFromFavorites: "Eliminar de favoritos",
    goldCalculator: "Calculadora de Oro",
    currencyConverter: "Convertidor de Moneda",
    charts: "Gráficos",
    timeframe: "Período",
    day: "1 Día",
    week: "1 Semana",
    month: "1 Mes",
    sixMonths: "6 Meses",
    year: "1 Año",
    language: "Idioma",
    theme: "Tema",
    light: "Claro",
    dark: "Oscuro",
    system: "Sistema",
    highPrice: "Alto",
    lowPrice: "Bajo",
    avgPrice: "Promedio",
    home: "Inicio",
    settings: "Ajustes",
    languageChanged: "Idioma cambiado a",
    goldPricePerGram: "Precio del oro por gramo"
  },
  zh: {
    goldPrice: "黄金价格",
    currentPrice: "当前价格",
    change: "变化",
    changePercent: "变化百分比",
    buy: "买入",
    sell: "卖出",
    currency: "货币",
    weight: "重量",
    purity: "纯度",
    calculate: "计算",
    result: "结果",
    from: "从",
    to: "至",
    amount: "金额",
    convert: "转换",
    popular: "热门",
    favorites: "收藏",
    addToFavorites: "添加到收藏",
    removeFromFavorites: "从收藏中移除",
    goldCalculator: "黄金计算器",
    currencyConverter: "货币转换器",
    charts: "图表",
    timeframe: "时间范围",
    day: "1天",
    week: "1周",
    month: "1月",
    sixMonths: "6个月",
    year: "1年",
    language: "语言",
    theme: "主题",
    light: "浅色",
    dark: "深色",
    system: "系统",
    highPrice: "最高价",
    lowPrice: "最低价",
    avgPrice: "平均价",
    home: "首页",
    settings: "设置",
    languageChanged: "语言已更改为",
    goldPricePerGram: "每克黄金价格"
  }
};

// Timeframes for charts
export const timeframes = [
  { value: "1d", label: "1 Day" },
  { value: "1w", label: "1 Week" },
  { value: "1m", label: "1 Month" },
  { value: "6m", label: "6 Months" },
  { value: "1y", label: "1 Year" }
];

// Gold images for the application
export const goldImages = [
  "/lovable-uploads/133715b9-b3ee-4c65-9981-e9df84e11795.png",
  "/lovable-uploads/408ed4f9-6669-45df-979f-458a73b393ee.png",
  "/lovable-uploads/6fb8c3ed-1670-4df9-8394-4f7ac33d7206.png",
  "/lovable-uploads/7a7e2918-3118-4784-988d-4094552314c2.png",
  "/lovable-uploads/82dd0c5b-0351-45cc-833c-2e7e67aa21de.png",
  "/lovable-uploads/a1d132b9-6145-4ec1-9efa-d48d5108d880.png",
  "/lovable-uploads/b7db9dba-cfe2-4a05-9dcd-9ec276bd6854.png",
  "/lovable-uploads/dba310bb-687f-4abf-9492-5498981fab0c.png",
  "/lovable-uploads/e797d011-901c-48ef-a1f6-96312c96b850.png",
  "/lovable-uploads/ed8a2eb4-1bc0-45e6-b78c-5e2e303c06ef.png",
  "/lovable-uploads/fd3e9720-0ce6-4d39-bd25-2179a6ecc4ea.png"
];
