
export const currencySymbols: Record<string, string> = {
  USD: "US Dollar",
  EUR: "Euro",
  GBP: "British Pound",
  JPY: "Japanese Yen",
  AUD: "Australian Dollar",
  CAD: "Canadian Dollar",
  CHF: "Swiss Franc",
  CNY: "Chinese Yuan",
  INR: "Indian Rupee",
  MAD: "Moroccan Dirham",
  AED: "UAE Dirham",
  SAR: "Saudi Riyal",
  EGP: "Egyptian Pound",
  TRY: "Turkish Lira",
  RUB: "Russian Ruble",
  BRL: "Brazilian Real",
  MXN: "Mexican Peso",
  ZAR: "South African Rand",
  SGD: "Singapore Dollar",
  HKD: "Hong Kong Dollar",
  BTC: "Bitcoin",
  ETH: "Ethereum"
};

export const goldUnits = [
  { value: "gram", label: "Gram" },
  { value: "ounce", label: "Troy Ounce" },
  { value: "kilo", label: "Kilogram" }
];

export const timeframes = [
  { value: "1d", label: "1 Day" },
  { value: "1w", label: "1 Week" },
  { value: "1m", label: "1 Month" },
  { value: "6m", label: "6 Months" },
  { value: "1y", label: "1 Year" }
];

export const conversionFactors = {
  gram: 1,
  ounce: 31.1035,
  kilo: 1000
};

export const countries = [
  { code: "US", name: "United States", currency: "USD", flag: "🇺🇸" },
  { code: "EU", name: "European Union", currency: "EUR", flag: "🇪🇺" },
  { code: "GB", name: "United Kingdom", currency: "GBP", flag: "🇬🇧" },
  { code: "JP", name: "Japan", currency: "JPY", flag: "🇯🇵" },
  { code: "IN", name: "India", currency: "INR", flag: "🇮🇳" },
  { code: "AU", name: "Australia", currency: "AUD", flag: "🇦🇺" },
  { code: "CA", name: "Canada", currency: "CAD", flag: "🇨🇦" },
  { code: "CH", name: "Switzerland", currency: "CHF", flag: "🇨🇭" },
  { code: "CN", name: "China", currency: "CNY", flag: "🇨🇳" },
  { code: "MA", name: "Morocco", currency: "MAD", flag: "🇲🇦" },
  { code: "AE", name: "United Arab Emirates", currency: "AED", flag: "🇦🇪" },
  { code: "SA", name: "Saudi Arabia", currency: "SAR", flag: "🇸🇦" },
  { code: "EG", name: "Egypt", currency: "EGP", flag: "🇪🇬" },
  { code: "TR", name: "Turkey", currency: "TRY", flag: "🇹🇷" },
  { code: "RU", name: "Russia", currency: "RUB", flag: "🇷🇺" },
  { code: "BR", name: "Brazil", currency: "BRL", flag: "🇧🇷" },
  { code: "MX", name: "Mexico", currency: "MXN", flag: "🇲🇽" },
  { code: "ZA", name: "South Africa", currency: "ZAR", flag: "🇿🇦" },
  { code: "SG", name: "Singapore", currency: "SGD", flag: "🇸🇬" },
  { code: "HK", name: "Hong Kong", currency: "HKD", flag: "🇭🇰" }
];

export const languages = [
  { code: "en", name: "English", flag: "🇺🇸" },
  { code: "fr", name: "Français", flag: "🇫🇷" },
  { code: "es", name: "Español", flag: "🇪🇸" },
  { code: "ar", name: "العربية", flag: "🇸🇦" },
  { code: "zh", name: "中文", flag: "🇨🇳" }
];

export const goldImages = [
  { id: "gold-bars", src: "https://images.unsplash.com/photo-1610375461246-83df859d849d", alt: "Gold Bars" },
  { id: "gold-coins", src: "https://images.unsplash.com/photo-1612696874005-d659af6d2f7c", alt: "Gold Coins" },
  { id: "gold-jewelry", src: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f", alt: "Gold Jewelry" },
  { id: "gold-ingot", src: "https://images.unsplash.com/photo-1574362848149-11496d93a7c7", alt: "Gold Ingot" },
  { id: "gold-bullion", src: "https://images.unsplash.com/photo-1618160702438-9b02ab6515c9", alt: "Gold Bullion" },
  { id: "gold-bars-stack", src: "https://images.unsplash.com/photo-1589279715734-6631a314dfa2", alt: "Stack of Gold Bars" },
  { id: "gold-investments", src: "https://images.unsplash.com/photo-1582281171754-405cb2a75fb1", alt: "Gold Investment" },
  { id: "gold-nuggets", src: "https://images.unsplash.com/photo-1610375461527-3e40ef5a3bd7", alt: "Gold Nuggets" }
];

export const translations = {
  en: {
    goldPriceTracker: "Gold Price Tracker",
    trackRealTime: "Track real-time gold prices across different countries and units",
    currentGoldPrice: "Current Gold Price",
    country: "Country",
    unit: "Unit",
    currency: "Currency",
    priceTrend: "Price Trend",
    historicalGoldPrice: "Historical gold price",
    goldPriceByUnit: "Gold Price by Unit",
    compareGoldPrices: "Compare gold prices in different measurement units",
    priceStatistics: "Price Statistics",
    keyMetrics: "Key metrics for gold price in",
    average: "Average",
    minimum: "Minimum",
    maximum: "Maximum",
    change: "Change",
    search: "Search",
    language: "Language",
    selectCountry: "Select country",
    selectUnit: "Select unit",
    selectLanguage: "Select language",
    lastUpdated: "Last updated",
    gram: "Gram",
    ounce: "Troy Ounce",
    kilogram: "Kilogram",
    days: "Days",
    priceOf: "Price of",
    pricePerGram: "Price per Gram",
    pricePerOunce: "Price per Ounce",
    pricePerKilo: "Price per Kilogram",
    sortAscending: "Sort Ascending",
    sortDescending: "Sort Descending",
    // Currency converter translations
    currencyConverter: "Currency Converter",
    convertRealTime: "Convert between different currencies in real-time",
    convertCurrency: "Convert Currency",
    enterAmountDesc: "Enter amount and select currencies to convert",
    amount: "Amount",
    enterAmount: "Enter amount",
    from: "From",
    to: "To",
    selectCurrency: "Select currency",
    swapCurrencies: "Swap currencies",
    converting: "Converting...",
    convert: "Convert",
    popularConversionRates: "Popular Conversion Rates",
    quickReference: "Quick reference for commonly used currency pairs",
    use: "Use",
    favoriteCurrencies: "Favorite Currencies",
    quickAccess: "Quick access to your most used currencies",
    noFavorites: "No favorites added yet",
    addFavorite: "Add favorite",
    // Gold image gallery translations
    goldImageGallery: "Gold Image Gallery",
    previousImage: "Previous Image",
    nextImage: "Next Image"
  },
  fr: {
    goldPriceTracker: "Suivi du Prix de l'Or",
    trackRealTime: "Suivez les prix de l'or en temps réel dans différents pays et unités",
    currentGoldPrice: "Prix Actuel de l'Or",
    country: "Pays",
    unit: "Unité",
    currency: "Devise",
    priceTrend: "Tendance des Prix",
    historicalGoldPrice: "Prix historique de l'or",
    goldPriceByUnit: "Prix de l'Or par Unité",
    compareGoldPrices: "Comparez les prix de l'or dans différentes unités de mesure",
    priceStatistics: "Statistiques des Prix",
    keyMetrics: "Indicateurs clés pour le prix de l'or en",
    average: "Moyenne",
    minimum: "Minimum",
    maximum: "Maximum",
    change: "Variation",
    search: "Rechercher",
    language: "Langue",
    selectCountry: "Sélectionner un pays",
    selectUnit: "Sélectionner une unité",
    selectLanguage: "Sélectionner une langue",
    lastUpdated: "Dernière mise à jour",
    gram: "Gramme",
    ounce: "Once Troy",
    kilogram: "Kilogramme",
    days: "Jours",
    priceOf: "Prix de",
    pricePerGram: "Prix par Gramme",
    pricePerOunce: "Prix par Once",
    pricePerKilo: "Prix par Kilogramme",
    sortAscending: "Tri Ascendant",
    sortDescending: "Tri Descendant",
    // Currency converter translations
    currencyConverter: "Convertisseur de Devises",
    convertRealTime: "Convertissez entre différentes devises en temps réel",
    convertCurrency: "Convertir la Devise",
    enterAmountDesc: "Saisissez le montant et sélectionnez les devises à convertir",
    amount: "Montant",
    enterAmount: "Saisir le montant",
    from: "De",
    to: "À",
    selectCurrency: "Sélectionner la devise",
    swapCurrencies: "Échanger les devises",
    converting: "Conversion en cours...",
    convert: "Convertir",
    popularConversionRates: "Taux de Conversion Populaires",
    quickReference: "Référence rapide pour les paires de devises couramment utilisées",
    use: "Utiliser",
    favoriteCurrencies: "Devises Favorites",
    quickAccess: "Accès rapide à vos devises les plus utilisées",
    noFavorites: "Pas encore de favoris ajoutés",
    addFavorite: "Ajouter aux favoris",
    // Gold image gallery translations
    goldImageGallery: "Galerie d'Images d'Or",
    previousImage: "Image Précédente",
    nextImage: "Image Suivante"
  },
  es: {
    goldPriceTracker: "Seguimiento del Precio del Oro",
    trackRealTime: "Sigue los precios del oro en tiempo real en diferentes países y unidades",
    currentGoldPrice: "Precio Actual del Oro",
    country: "País",
    unit: "Unidad",
    currency: "Moneda",
    priceTrend: "Tendencia de Precios",
    historicalGoldPrice: "Precio histórico del oro",
    goldPriceByUnit: "Precio del Oro por Unidad",
    compareGoldPrices: "Compara los precios del oro en diferentes unidades de medida",
    priceStatistics: "Estadísticas de Precios",
    keyMetrics: "Métricas clave para el precio del oro en",
    average: "Promedio",
    minimum: "Mínimo",
    maximum: "Máximo",
    change: "Cambio",
    search: "Buscar",
    language: "Idioma",
    selectCountry: "Seleccionar país",
    selectUnit: "Seleccionar unidad",
    selectLanguage: "Seleccionar idioma",
    lastUpdated: "Última actualización",
    gram: "Gramo",
    ounce: "Onza Troy",
    kilogram: "Kilogramo",
    days: "Días",
    priceOf: "Precio de",
    pricePerGram: "Precio por Gramo",
    pricePerOunce: "Precio por Onza",
    pricePerKilo: "Precio por Kilogramo",
    sortAscending: "Orden Ascendente",
    sortDescending: "Orden Descendente",
    // Currency converter translations
    currencyConverter: "Conversor de Divisas",
    convertRealTime: "Convierte entre diferentes divisas en tiempo real",
    convertCurrency: "Convertir Divisa",
    enterAmountDesc: "Ingrese cantidad y seleccione divisas para convertir",
    amount: "Cantidad",
    enterAmount: "Ingrese cantidad",
    from: "De",
    to: "A",
    selectCurrency: "Seleccionar divisa",
    swapCurrencies: "Intercambiar divisas",
    converting: "Convirtiendo...",
    convert: "Convertir",
    popularConversionRates: "Tasas de Conversión Populares",
    quickReference: "Referencia rápida para pares de divisas comúnmente usados",
    use: "Usar",
    favoriteCurrencies: "Divisas Favoritas",
    quickAccess: "Acceso rápido a sus divisas más utilizadas",
    noFavorites: "Aún no se han agregado favoritos",
    addFavorite: "Añadir a favoritos",
    // Gold image gallery translations
    goldImageGallery: "Galería de Imágenes de Oro",
    previousImage: "Imagen Anterior",
    nextImage: "Imagen Siguiente"
  },
  ar: {
    goldPriceTracker: "متتبع أسعار الذهب",
    trackRealTime: "تتبع أسعار الذهب في الوقت الحقيقي عبر مختلف البلدان والوحدات",
    currentGoldPrice: "سعر الذهب الحالي",
    country: "البلد",
    unit: "وحدة",
    currency: "العملة",
    priceTrend: "اتجاه السعر",
    historicalGoldPrice: "سعر الذهب التاريخي",
    goldPriceByUnit: "سعر الذهب حسب الوحدة",
    compareGoldPrices: "قارن أسعار الذهب بوحدات قياس مختلفة",
    priceStatistics: "إحصائيات الأسعار",
    keyMetrics: "المقاييس الرئيسية لسعر الذهب في",
    average: "المتوسط",
    minimum: "الحد الأدنى",
    maximum: "الحد الأقصى",
    change: "التغيير",
    search: "بحث",
    language: "اللغة",
    selectCountry: "اختر البلد",
    selectUnit: "اختر الوحدة",
    selectLanguage: "اختر اللغة",
    lastUpdated: "آخر تحديث",
    gram: "جرام",
    ounce: "أونصة تروي",
    kilogram: "كيلوجرام",
    days: "أيام",
    priceOf: "سعر",
    pricePerGram: "السعر لكل جرام",
    pricePerOunce: "السعر لكل أونصة",
    pricePerKilo: "السعر لكل كيلوجرام",
    sortAscending: "ترتيب تصاعدي",
    sortDescending: "ترتيب تنازلي",
    // Currency converter translations
    currencyConverter: "محول العملات",
    convertRealTime: "تحويل بين العملات المختلفة في الوقت الحقيقي",
    convertCurrency: "تحويل العملة",
    enterAmountDesc: "أدخل المبلغ واختر العملات للتحويل",
    amount: "المبلغ",
    enterAmount: "أدخل المبلغ",
    from: "من",
    to: "إلى",
    selectCurrency: "اختر العملة",
    swapCurrencies: "تبديل العملات",
    converting: "جاري التحويل...",
    convert: "تحويل",
    popularConversionRates: "أسعار التحويل الشائعة",
    quickReference: "مرجع سريع لأزواج العملات المستخدمة بشكل شائع",
    use: "استخدام",
    favoriteCurrencies: "العملات المفضلة",
    quickAccess: "وصول سريع للعملات الأكثر استخدامًا",
    noFavorites: "لم تتم إضافة مفضلات بعد",
    addFavorite: "أضف إلى المفضلة",
    // Gold image gallery translations
    goldImageGallery: "معرض صور الذهب",
    previousImage: "الصورة السابقة",
    nextImage: "الصورة التالية"
  },
  zh: {
    goldPriceTracker: "黄金价格追踪器",
    trackRealTime: "追踪不同国家和单位的实时黄金价格",
    currentGoldPrice: "当前黄金价格",
    country: "国家",
    unit: "单位",
    currency: "货币",
    priceTrend: "价格趋势",
    historicalGoldPrice: "历史黄金价格",
    goldPriceByUnit: "按单位计算的黄金价格",
    compareGoldPrices: "比较不同计量单位的黄金价格",
    priceStatistics: "价格统计",
    keyMetrics: "黄金价格的关键指标，以",
    average: "平均值",
    minimum: "最低",
    maximum: "最高",
    change: "变化",
    search: "搜索",
    language: "语言",
    selectCountry: "选择国家",
    selectUnit: "选择单位",
    selectLanguage: "选择语言",
    lastUpdated: "最后更新",
    gram: "克",
    ounce: "金衡盎司",
    kilogram: "千克",
    days: "天",
    priceOf: "价格",
    pricePerGram: "每克价格",
    pricePerOunce: "每盎司价格",
    pricePerKilo: "每千克价格",
    sortAscending: "升序排序",
    sortDescending: "降序排序",
    // Currency converter translations
    currencyConverter: "货币转换器",
    convertRealTime: "实时转换不同货币",
    convertCurrency: "转换货币",
    enterAmountDesc: "输入金额并选择要转换的货币",
    amount: "金额",
    enterAmount: "输入金额",
    from: "从",
    to: "至",
    selectCurrency: "选择货币",
    swapCurrencies: "交换货币",
    converting: "转换中...",
    convert: "转换",
    popularConversionRates: "热门转换汇率",
    quickReference: "常用货币对的快速参考",
    use: "使用",
    favoriteCurrencies: "收藏货币",
    quickAccess: "快速访问您最常用的货币",
    noFavorites: "尚未添加收藏",
    addFavorite: "添加收藏",
    // Gold image gallery translations
    goldImageGallery: "黄金图片展示",
    previousImage: "上一张图片",
    nextImage: "下一张图片"
  }
};
