// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxrhfxwwfcnvbssudjvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4cmhmeHd3ZmNudmJzc3VkanZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMTY5MDEsImV4cCI6MjA1OTU5MjkwMX0.rmR9KiisRYjlESFWHKLaQG9bkS17nCx2omuJ8M4xUcE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);